server:
  port: 8100

spring:
  application:
    name: yunyao-gateway-service
  # 数据库设置
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  # spring cloud alibaba 等服务设置
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: yunyao-search-service #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8082          #匹配后提供服务的路由地址
          uri: lb://yunyao-search-service #匹配后提供服务的路由地址
          predicates:
            - Path=/search/**      # 断言，路径相匹配的进行路由
          filters:
            - StripPrefix=1
        - id: yunyao-behavior-service #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
            #          uri: http://localhost:8082          #匹配后提供服务的路由地址
          uri: lb://yunyao-behavior-service #匹配后提供服务的路由地址
          predicates:
            - Path=/behavior/**      # 断言，路径相匹配的进行路由
          filters:
            - StripPrefix=1
    nacos:
      discovery:
        server-addr: localhost:8848 #Nacos服务注册中心地址
    sentinel:
      transport:
        dashboard: localhost:8080 #配置Sentinel dashboard地址
        port: 8719
      datasource:
        ds1:
          nacos:
            server-addr: localhost:8848
            dataId: ${spring.application.name}
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: flow

management:
  endpoints:
    web:
      exposure:
        include: '*'
feign:
  httpclient:
    enabled: false