############################## Environment ##############################
# dev   Development
# test  test
# pre   pre-环release
# prod  production
spring:
  profiles:
    active: dev
    include: common
encryption:
  key: 123